--- #YAML:1.0
name:               HTML-Query
version:            0.02
abstract:           perform jQuery-like queries on HTML::Element trees
author:
    - Andy Wardley <abw@wardley.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Badger:      0.03
    HTML::Tree:  3.23
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
